AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Demonstrate a basic trivia skill built with the ASK NodeJS SDK
Resources:
  alexaskillkitsdktriviaskill:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      CodeUri: .
      Description: Demonstrate a basic trivia skill built with the ASK NodeJS SDK
      MemorySize: 128
      Timeout: 10
